name: Fast Personal Build

on:
  push:
    branches:
      - '*-dev'
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21

      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==

      - name: Build Debug APK
        run: ./gradlew assembleLawnWithQuickstepGithubDebug

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Custom-Lawnchair-App
          path: build/outputs/apk/**/*.apk
